name: gophermart
services: 
  db_gophermart:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: gophermart
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: gophermart
    ports: 
      - "5433:5432"
    networks:
      - backend
  gophermart:
    image: gophermart:latest
    restart: always
    build:
      context: .
      dockerfile: gophermart.Dockerfile
    environment:
      RUN_ADDRESS: gophermart:8080
      ACCRUAL_SYSTEM_ADDRESS: accrual:8081
      DATABASE_URI: postgresql://gophermart:12345678@db_gophermart:5432/gophermart?sslmode=disable
      LOG_LEVEL: INFO
    depends_on:
      - db_gophermart
    ports: 
      - "8080:8080"
    networks:
      - backend
  db_accrual:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: accrual
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: accrual
    ports: 
      - "5434:5432"
    networks:
      - backend
  accrual:
    image: accrual:latest
    restart: always
    build:
      context: .
      dockerfile: accrual.Dockerfile
    environment:
      RUN_ADDRESS: accrual:8081
      DATABASE_URI: postgresql://accrual:12345678@db_accrual:5432/accrual?sslmode=disable
    depends_on:
      - db_accrual
    ports: 
      - "8081:8081"
    networks:
      - backend
networks:
  backend: 
    driver: bridge
    ipam:
      driver: default
      config: 
        - subnet: 10.15.32.0/24
